services:
  postgres:
    image: postgres:16-alpine
    container_name: pipelinex-postgres
    environment:
      POSTGRES_DB: pipelinex
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pipelinex-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pipelinex"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  pipelinex-postgres-data:
