spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: test
    password: test
    hikari:
      connection-timeout: 60000
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

app:
  seed:
    enabled: false
